### ISSUE TITLE
onChange event fires as onInput

### ISSUE THREAD

**Issue by robodna** [nsaritzky/solid-currency-input-field#1]
### Describe The Problem To Be Solved

The onChange event of a native input only gets dispatched if the user exits from the input or presses enter, and is browser dependent.  

### Suggest A Solution

The onChange event for solid-currency-input-field should only dispatch under those same parameters as it is expected behavior.  It currently gets dispatched in the same way the onInput event fires for native input elements.  The onValueChange event could be fired like onInput since that property name cannot be confused with onChange for native inputs.

Due to this missing onChange event, I am unable to use this component since converting a value such as '4.' transforms to just '4' if value is set programatically as in Number.parseFloat()

**Comment by nsaritzky** [comment]
This was a remnant of being ported over from React, where onInput and onChange are handled the same way. I've fixed it and added a separate onInput prop. I appreciate the feedback.
